= Big Data Infrastructure Exercises

We'll use this repository through our course.
Starting it from a small application to have something
bigger and more complex.


== How will the exercises be evaluated?

For the parts requiring code, I'll consider the following:

1. Start the application. It does not start -> 0 automatically
2. I'll run a series of validation tests against your application (6 points)
 * % of passed tests
3. Pass code linting (`ruff`, for best code practices) (1 points)
 * 0 -> 100%
 * 1-3 -> 80%
 * 4-5 -> 60%
 * 6-8 -> 50%
 * >8 -> 0%
4. Performance evaluation (1 point)
 * Ranked according to the best of youXXXXXXXXXXXXX
5. Tests you might have implemented (2 points)
 * Coverage % and completeness

Considerations:

* Late delivery not justified: -2 points per day


== Libraries

https://fastapi.tiangolo.com/[FastAPI] is one of the best libraries for building an API with Python.
It has a great documentation and enables us to build
type safe and documented APIs easily.



== Data
Use the `data/` folder to store your data.
It will not be uploaded to any git repository.
